### ISSUE TITLE
预训练模型model.ckpt

### ISSUE THREAD

**Issue by Hukongtao** [gengyanlei/Semi-Supervised-Semantic-Segmentation-GAN#1]
作者您好，我也想跑一下您的代码，但是我数据集比较少，您方便提供一下您的预训练模型么？

**Comment by Hukongtao** [comment]
或者发我QQ邮箱也可以。1821141394@qq.com。多谢你了。

**Comment by gengyanlei** [comment]
@Hukongtao 
你好，首先我不是本文作者，这篇论文有源码：pytorch版本的，其次，我的tensorflow代码与原文还是有区别的，网络与原文不同。你可以fine-tune tensorflow给出在imagenet上预训练的模型。

**Comment by gengyanlei** [comment]
@Hukongtao 
这是原文代码（pytorch版本的）：https://github.com/hfslyc/AdvSemiSeg

**Comment by Hukongtao** [comment]
@gengyanlei 了解了解。因为对Pytorch不是很熟，然后正好看到了您的tensorflow版本，就想着先用用你的试试效果。那我这边自己用VOC12的数据跑跑看先吧。

**Comment by watchmexiang** [comment]
您好，我也是因为对pytorch不熟悉，正好看到了您的tensorflow代码，你的网络架构是否是复现原文的，您的生成器替换的分割网络是哪一种分割网络，期待您的回复，谢谢

**Comment by gengyanlei** [comment]
@zhangyuqiqiyuzhang 你好，我的生成器是U_Net，也可以用原始论文的。基本思路按照原始论文弄得，但是有些细节 感觉不是很相同。

**Comment by watchmexiang** [comment]
谢谢您的回复，我还想问一下您的程序用的数据集从哪里下载啊，我看您的数据集地址有两个dataset_path和dataset_nl_path，他们分别代表什么啊，我输入的数据集也必须是hdf5格式吗

**Comment by gengyanlei** [comment]
@zhangyuqiqiyuzhang  前者是含有标签的数据集，后者是不含标签的数据集。和原始论文是一个思路，分开数据。

**Comment by watchmexiang** [comment]
麻烦您了，那您用的数据集是从哪里下载的啊，我这里暂时没有hdf5格式的文件，都是.jpg格式的图片，从哪里可以下载到该程序可以使用的数据集，我想先跑下您的程序，谢谢您了

**Comment by gengyanlei** [comment]
@zhangyuqiqiyuzhang hdf5是一种存储格式，把jpg等格式的保存成hdf5就可以，或者你可以不用hdf5存储，直接本地读取也可以。

**Comment by peterwsn** [comment]
I have the same problem, and I don't know how to modify the program to read the image and the true value directly. Can you solve it? @zhangyuqiqiyuzhang @gengyanlei

**Comment by gengyanlei** [comment]
@peterwsn  https://github.com/gengyanlei/leilei/blob/master/batch_imread_dataset.py
请适当修改。图片与对应标签图 名字要一样；分成2个文件夹放置；然后有一个txt文件保存图片名称。

**Comment by gengyanlei** [comment]
标签图为单通道灰度值图，从0开始。
数据增强 可以额外添加。

**Comment by watchmexiang** [comment]
谢谢您的回复，我已经有了不少的收获，我还想再问您一下含有标签的那个数据集（dataset_path）我是需要即输入原图又输入标签图还是只输入标签图，第二个数据集（dataset_nl_path）我只需要给出原始图像就可以了是吧，谢谢

**Comment by gengyanlei** [comment]
@zhangyuqiqiyuzha 无论哪个数据，我都滑动裁剪成256*256大小，dataset_path 这里有图像文件 和 对应的标签图文件；同时读取；而无标签的只需要读取图像就可以。

**Comment by watchmexiang** [comment]
感谢您的回复，我已经成功进行了训练，请问进行测试是直接使用您写的restore.py文件吗，测试用的数据直接给出原始图像就可以吗，谢谢

**Comment by gengyanlei** [comment]
@zhangyuqiqiyuzha 如果测试集影像都是1024*1024  或者 256*256 或者256*512 这样的  一张张测试即可；如果影像是1003*2001这样的，建议滑动预测。此外，我写的代码训练如果不成功，建议重新修改学习率的更新函数，我的学习率设置和原文的有点区别。

**Comment by watchmexiang** [comment]
我用您的程序进行了测试，测试结果并不成功，我建立三个文件夹，分别存放原图（测试图），测试结果图，和标签图，然而运行测试程序后发现写入进测试结果文件夹的图片都是分辨率为1*4的图片（空图像），请问是我训练的模型出现问题，开始我的测试方式有问题

**Comment by gengyanlei** [comment]
你可以测试时，一步步测试，在ipython中输出一下，看看是哪里出现了错误。

**Comment by watchmexiang** [comment]
您好，您的测试程序的第三十二行  cv2.imwrite(os.path.join(test_path,'pred',names[i]))是不是在后面少加了一个predict，我将其改为了 cv2.imwrite(os.path.join(test_path,'pred',names[i])，predict），然而这样改，输出的全为黑色图像，我在训练的时候只用到了监督部分，class_number为2，而没有进行半监督的训练，训练过程的损失也都正常，您能帮我判断以下是训练的问题还是测试程序的问题吗，再次感谢您的帮助，给您填了许多麻烦，谢谢您了

**Comment by watchmexiang** [comment]
还是因为我只跑了有监督的部分，而没有跑半监督因此在测试程序中predict = np.array(sess.run(pred, feed_dict={image: img, is_training: False}))[0]  # H*W这个也要进行相应的调整，如果有可能的话，您能加下我的联系方式吗，qq1264754202，我想更好的向您请教一下程序的问题，当然您在这里回复我也是非常感谢的，期待您的回复，谢谢

**Comment by gengyanlei** [comment]
@zhangyuqiqiyuzhang 非常感谢你发现了问题，我复制的时候可能少复制了。测试输出是单通道灰度图，你可以把灰度图转为RGB三通道的图像。灰度图是按照0123...类别数来的。

**Comment by gengyanlei** [comment]
H,W = predict.shape
RGB = np.zeros([H,W,3],dtype=np.uint8)
RGB[predict==1]=np.array([255,0,0])
cv2.imwrite(path, RGB)   这样就是彩色了。

**Comment by watchmexiang** [comment]
好像不是通道数的问题，我训练的标签图为两类，即目标和背景的恢复图像，训练过程的两个损失也都是正常范围，然而我进行测试的时候发现没有测试结果，测试得到的图像是全黑的，不知道是什么问题

**Comment by gengyanlei** [comment]
@zhangyuqiqiyuzhang 
那不清楚了，也可能是我的代码的问题。因为这个半监督训练更新学习率与pytorch的还不太一样，我照猫画虎的写的学习率更新代码。

**Comment by gengyanlei** [comment]
你最好在ipython中一步步输出结果看看

**Comment by gengyanlei** [comment]
@zhangyuqiqiyuzhang  可能是我的主函数的问题，建议你看看  这些GAN。
https://github.com/hwalsuklee/tensorflow-generative-model-collections

**Comment by watchmexiang** [comment]
那好吧 那我自己研究吧 您用您自己的数据集进行测试这个程序，结果都是好的是吧

**Comment by watchmexiang** [comment]
您好，请问您当时进行测试时，测试结果是什么样的啊，是一张语义分割图还是

**Comment by gengyanlei** [comment]
@zhangyuqiqiyuzhang  G的输出是语义分割图，但是感觉你应该先弄弄FCN类型，然后再看看GAN的类型，最后你自己再复现这个代码。无论啥框架，基本结构都是一样的，无论损失函数，网络等。

**Comment by watchmexiang** [comment]
![QQ截图20190321092620](https://user-images.githubusercontent.com/35333596/54729057-4419ff00-4bbc-11e9-9b77-eb8e751c5fe4.png)
![QQ截图20190321092641](https://user-images.githubusercontent.com/35333596/54729059-4bd9a380-4bbc-11e9-920a-f1698aaa4db1.png)这是我的两个损失函数的截图您看一下这个有问题吗

**Comment by gengyanlei** [comment]
@zhangyuqiqiyuzhang  我只是复现了代码，但是我不能全部确定  关于学习率设置和优化器 这一块是否正确。pytorch代码里面是2个优化器，但是这里我只能设置成3个优化器实现半监督。如果不涉及半监督，你可以参考其他代码，我总感觉自己写的记录损失 的代码很乱。
G的损失应该是逐渐下降，趋于稳定；而D的损失应该是从大慢慢往下降低，但是损失上下震荡，最后实现一个动态平衡。

**Comment by Hukongtao** [comment]
@zhangyuqiqiyuzhang 测试结果全黑是不是因为你的像素值是0和1啊，你需要把像素值为1的点改为255才能显示出来啊

**Comment by watchmexiang** [comment]
您好，感谢您的回复，我加上了predict[np.where(predict=1)]=255这句，还是没有效果，我单步调试发现我的prediction这个数组中所有的值都是0，我还在找问题的原因，请问您测试成功了 @Hukongtao

**Comment by gengyanlei** [comment]
应该加 predict[predict==1]=255;建议你还是看看别人用于图像生成的GAN（tf版本的），然后根据自己的理解去重写代码。

**Comment by Hukongtao** [comment]
@zhangyuqiqiyuzhang 我没跑这个代码诶

**Comment by watchmexiang** [comment]
您训练和测试过这个程序吧，效果都正常是吧，如果您实验都是正常的，我就在您的基础上再修改一下，或是换一些数据在进行一些实验 @gengyanlei

**Comment by gengyanlei** [comment]
我用了3天复现了这个代码（参考了tf版本的GAN图像生成相关代码以及pytorch的原文代码），但是只是跑通了，跑了一个小时，我就中断了，没有测试这个代码。我从caffe转到tf，又从tf转到pytorch。

**Comment by watchmexiang** [comment]
@gengyanlei 好的 谢谢您一直以来的帮助，我想问个问题，我看它pytorch版的源码，它使用的voc数据集，它的输入的标签图是一种单通道的灰度图，是用灰度来表示的标签，而我自己的数据集还是传统的利用颜色来表示标签信息，不知道您是否知道如何将我的这种标签转化为他使用的单通道灰度标签，或者我可以在程序中把读他那种标签的方式改回为读我颜色标签的方法，谢谢了

**Comment by gengyanlei** [comment]
@zhangyuqi
pytorch要求必须是单通道的灰度图标签，从0开始，它的内部代码会把这个标签转为one-hot类型的。
你必须要把数据标签转成单通道的图。

**Comment by watchmexiang** [comment]
@gengyanlei 那请问如何能够进行转换啊，您有没有相关的代码能给我参考以下啊

**Comment by gengyanlei** [comment]
按照不同的颜色类别转换啊。voc也有对应的颜色 对应的类别。其他的数据 或者自己制作的数据  自己处理一下就可以   做个逻辑变换
